image: asciidoctor/docker-asciidoctor:1.84

stages: [build, deploy]

build_docs:
  stage: build
  script:
    - set -euo pipefail

    # HTML -> public/index.html  (images embedded)
    - |
      asciidoctor \
        -a data-uri \
        -a toc=left \
        -a sectnums \
        -a reproducible \
        -a icons=font \
        -a source-highlighter=Pygments \
        -a experimental \
        -r asciidoctor-diagram \
        -a imagesdir=images \
        -a imagesoutdir=.asciidoctor/diagram \
        -a diagram-cachedir=.asciidoctor/diagram \
        -D public \
        -R doc \
        doc/**/*.adoc

    # PDF -> build/pdf/index.pdf
    - mkdir -p build/pdf public/pdf
    - |
      asciidoctor-pdf \
        -r asciidoctor-diagram \
        -a imagesdir=images \
        -a imagesoutdir=.asciidoctor/diagram \
        -a diagram-cachedir=.asciidoctor/diagram \
        -D build/pdf \
        -R doc \
        doc/**/*.adoc
    - cp -a build/pdf/*.pdf public/pdf/ || true

  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - public/**/*
      - build/pdf/*.pdf

  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'

deploy_pages:
  stage: deploy
  needs: [build_docs]
  script:
    - echo "Publishing GitLab Pages from ./public"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
  pages: true