Lilli
7lilli7
Online

LeonieAbels — 26.11.2025 12:11
Hey Lilli,
Nur zur Info, ich hatte gestern mit der restlichen Integrationsprojektgruppe ne spontane Besprechung nach den Vorträgen. Osama hat klar gemacht, das er sehr frustriert ist über die ungleiche Menge an Arbeit die manche in der Gruppe in das Projekt stecken, dass er nicht mehr zu Gruppenterminen kommt und er bereit wäre, das ganze zu Klinger zu eskalieren.
Ich hab ihm gesagt, dass ich das nachvollziehen kann und ihn gebeten, das noch nicht zu tun.
Ich hab mich mit Mattis und Benedikt für heute verabredet und wir sehen was wir tun können, um die Lücke an Workload zwischen den Gruppenmitgliedern ein bisschen zu schließen.

Falls du Vorschläge hast, welche Sachen noch erledigt werden müssen oder welche Aufgaben wir dir abnehmen können, sag gern Bescheid. Du hast dich zwar nicht beschwert, aber ich stimme Osama absolut zu, dass ihr beide bei weitem am meisten beigetragen habt bisher. Ansonsten sehen wir uns morgen in der Vorlesung 🙂
Lilli — 26.11.2025 12:23
Hey,
also es wäre super, wenn Mattis das Thema mit den Ereignissen fertig stellen könnte. Das hatte ja meine ich noch nicht funktioniert. Wir sollte auf jeden Fall einen Punkt erreichen, bei dem alle Testfälle durchlaufen. Mattis und Benedikt sollten jetzt wo sie Ubi und das Kino erledigt haben, wieder mehr Zeit haben.

Es gab ja auch noch den Punkt zum Anlegen von neuen Ereignissen. Da müssten wir nochmal schauen, wie man das umsetzten könnte
LeonieAbels — 13:52
@startuml

participant app as "Android App"
participant bro as "MQTT Broker"
participant iot as "IoT Device"


activate iot


iot -> bro : connect (clean start,)
'request problem information, will, will delay interval?
activate bro
note right
"User presses button on iot device"
end note
bro -> iot : connack
'reason string
iot -> bro : subscribe (modus)
iot -> bro : subscribe (Eventlist)
iot -> bro : subscribe (Sensorlist)



app -> bro : connect
activate app
note left
"User opens app"
end note
bro -> app : connack
app -> bro : publish (Sensorlist: list)
'qos 0: alt most once deliv, qos 1: at least once deliv.,qos 2: exactly once
bro -> iot : publish (Sensorlist: list)
app -> bro : publish (Eventlist: list)
bro -> iot : publish (Eventlist: list)
app -> bro : subscribe (sensorMag)
app -> bro : subscribe (sensorAcc)
app -> bro : subscribe (sensorGyro)
app -> bro : subscribe (Events)
app -> bro : publish (modus: I)
bro -> iot : publish (modus: I)
iot -> bro : publish (sensorMag: data)
note right
Sensors will be read and send continuously
end note
bro -> app : publish (sensorMag: data)
iot -> bro : publish (sensorAcc: data)
bro -> app : publish (sensorAcc: data)
iot -> bro : publish (sensorGyro: data)
bro -> app : publish (sensorGyro: data)
iot -> bro : publish (Event: data)
bro -> app : publish (Event: data)
...
app -> bro : publish (Modus: E)
bro -> iot : publish (Modus: E)
note right
Sensordaten werden weiterhin auf SD-Karte gespeichert,
aber nicht weiter gepublisht
end note
iot -> bro : publish (Event: data)


@enduml
